name: bohr.rocks deploy
on: 
  push:
  repository_dispatch:
    types: [bohr-dispatch]
permissions: write-all
jobs:
  deploy:
    name: Deploy on bohr.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: corepack enable

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm      
          
      - uses: bohr-io/action@main
        with:
          cli-version: '@bohr.io/bohr-dev@dev'